services:

  postgres:
        image: postgres:14.6-alpine
        volumes:
            -postgres_data:/var/lib/postgresql/data


  redis-app:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  app:
    build: .
    volumes:
      - .:/app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'

  celery:
    build: .
    command: ['celery', '--workdir=.', '-A', 'worker', '-l', 'INFO']
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - app
      - redis-app

  celery-beat:
    build: .
    command: ['celery', '--workdir=.', '-A', 'beat', '-l', 'INFO']
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - app
      - redis-app
      - celery