# Generated by Django 4.1.5 on 2023-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filechecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
