# Generated by Django 4.1.5 on 2023-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filechecker', '0003_alter_file_options_remove_file_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
